### ISSUE TITLE
[New role] Wannabe - the crew that wants to be an imposter

### ISSUE THREAD

**Issue by k-electron** [Anusien/Town-Of-Us#154] opened 2021-12-10 02:21 UTC
A crew role that looks like an imposter to the imposters. The wannabe can enter vents but not travel using vents.

Settings:
Sheriff kills Wannabe: On / Off (default)
Wannabe has imposter vision: On (default) / Off

**Comment by Anusien** [comment] 2021-12-15 18:20
https://github.com/Anusien/Town-Of-Us/issues/129

**Comment by Anusien** [comment] 2022-01-20 19:02
Dupe of #129

**Closed as completed by Anusien** 2022-01-20 19:02 UTC
